import type { BenchTask, BenchWorld, WritePolicy } from "./types.ts";

function world(writePolicy: WritePolicy = "direct_edit"): BenchWorld {
  return {
    creedName: "Avery's Creed",
    writePolicy,
    sections: [
      {
        id: "identity",
        name: "Identity",
        accent: "identity",
        permission: "direct",
        contentMarkdown: "Avery Chen is a product designer based in Manchester.",
      },
      {
        id: "goals",
        name: "Goals",
        accent: "projects",
        permission: "direct",
        contentMarkdown: "- Launch the accessibility toolkit by October.\n- Run a half marathon.",
      },
      {
        id: "work",
        name: "Work",
        accent: "stack",
        permission: "direct",
        contentMarkdown: "Leads product design at Northstar. Focused on accessible collaboration software.",
      },
      {
        id: "preferences",
        name: "Preferences",
        accent: "preferences",
        permission: "direct",
        contentMarkdown: "- Prefer concise answers with a recommendation first.\n- Use metric units.",
      },
      {
        id: "constraints",
        name: "Constraints",
        accent: "boundaries",
        permission: "direct",
        contentMarkdown: "- Avoid shellfish.\n- Keep recurring software spend below £80 per month.",
      },
      {
        id: "routines",
        name: "Routines",
        accent: "workflows",
        permission: "direct",
        contentMarkdown: "- Deep work on weekday mornings.\n- Long run on Sunday.",
      },
      {
        id: "old-notes",
        name: "Old notes",
        accent: "mono",
        permission: "direct",
        contentMarkdown: "Temporary conference packing list from 2024.",
      },
      {
        id: "private",
        name: "Private",
        accent: "rose",
        permission: "hidden",
        contentMarkdown: "This must never be visible to an agent.",
      },
    ],
    activity: [
      {
        id: "activity-1",
        sectionId: "goals",
        action: "accepted",
        summary: "Added the half-marathon goal.",
        createdAt: "2026-07-24T10:00:00.000Z",
      },
      {
        id: "activity-2",
        sectionId: "work",
        action: "direct",
        summary: "Updated Northstar role.",
        createdAt: "2026-07-20T09:00:00.000Z",
      },
    ],
    quality: [
      { sectionId: "identity", score: 82, gap: null },
      { sectionId: "goals", score: 74, gap: "Goals lack success criteria." },
      { sectionId: "work", score: 86, gap: null },
      { sectionId: "preferences", score: 67, gap: "Output preferences are thin." },
      { sectionId: "constraints", score: 91, gap: null },
      { sectionId: "routines", score: 58, gap: "Routines lack timing and triggers." },
    ],
  };
}

function proposalWorld() {
  const value = world("proposals_only");
  value.sections = value.sections.map((section) =>
    section.permission === "hidden" ? section : { ...section, permission: "propose" },
  );
  return value;
}

function task(
  value: Omit<BenchTask, "difficulty" | "forbiddenTools" | "answerTermGroups" | "maxTurns"> &
    Partial<Pick<BenchTask, "difficulty" | "forbiddenTools" | "answerTermGroups" | "maxTurns">>,
): BenchTask {
  return {
    difficulty: 1,
    forbiddenTools: [],
    answerTermGroups: [],
    maxTurns: 10,
    ...value,
  };
}

const MUTATIONS = [
  "propose_creed_update",
  "direct_edit_creed",
  "creed_update_section",
  "creed_create_section",
  "creed_delete_section",
  "creed_rename_section",
  "creed_recolor_section",
  "creed_append_to_section",
  "creed_reorder_section",
];

export const BENCH_TASKS: BenchTask[] = [
  task({
    id: "read-apply-constraints",
    title: "Read and apply constraints",
    family: "single-tool",
    prompt: "Recommend one restaurant cuisine for a team dinner and briefly explain why.",
    initialWorld: world(),
    requiredTools: ["read_creed"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["shellfish", "allergy"], ["avoid", "safe", "non-shellfish"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed"],
  }),
  task({
    id: "list-connected-creed",
    title: "Identify the connected Creed",
    family: "single-tool",
    prompt: "Which Creed is this connection scoped to? Give me only its name.",
    initialWorld: world(),
    requiredTools: ["list_creeds"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["Avery"]],
    mustReadCreed: false,
    toolsCovered: ["list_creeds"],
  }),
  task({
    id: "list-section-structure",
    title: "Inspect section structure",
    family: "single-tool",
    prompt: "List the visible Creed section names without quoting their contents.",
    initialWorld: world(),
    requiredTools: ["list_sections"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["Identity"], ["Goals"], ["Preferences"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections"],
  }),
  task({
    id: "targeted-section-read",
    title: "Read one section surgically",
    family: "single-tool",
    prompt: "What answer style does Avery prefer? Prefer the targeted section tool over a full profile read.",
    initialWorld: world(),
    requiredTools: ["creed_get_section"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["concise"], ["recommendation", "recommend"]],
    mustReadCreed: false,
    toolsCovered: ["creed_get_section"],
  }),
  task({
    id: "search-budget",
    title: "Search for a constraint",
    family: "single-tool",
    prompt: "Find Avery's recurring software budget using Creed search and report it.",
    initialWorld: world(),
    requiredTools: ["creed_search"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["£80", "80"], ["month", "monthly"]],
    mustReadCreed: false,
    toolsCovered: ["creed_search"],
  }),
  task({
    id: "recent-activity",
    title: "Inspect recent activity",
    family: "single-tool",
    prompt: "What was the most recent accepted Creed change?",
    initialWorld: world(),
    requiredTools: ["creed_get_recent_activity"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["half", "marathon"]],
    mustReadCreed: false,
    toolsCovered: ["creed_get_recent_activity"],
  }),
  task({
    id: "quality-report",
    title: "Find the weakest section",
    family: "single-tool",
    prompt: "Use the quality report to identify the weakest section and its main gap. Do not edit anything.",
    initialWorld: world(),
    requiredTools: ["creed_get_quality_report"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["Routines"], ["timing", "triggers"]],
    mustReadCreed: false,
    toolsCovered: ["creed_get_quality_report"],
  }),
  task({
    id: "write-policy",
    title: "Check write policy",
    family: "single-tool",
    prompt: "Is this Creed in proposal-only or direct-edit mode? Check the live policy.",
    initialWorld: proposalWorld(),
    requiredTools: ["get_write_policy"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["proposal"]],
    mustReadCreed: false,
    toolsCovered: ["get_write_policy"],
  }),
  task({
    id: "append-durable-preference",
    title: "Append a durable preference",
    family: "multi-tool",
    difficulty: 2,
    prompt: "From now on, always include keyboard shortcuts when explaining desktop workflows. Save that durable preference without losing existing preferences.",
    initialWorld: world(),
    requiredTools: ["read_creed"],
    expectedMutation: {
      operation: "append",
      sectionId: "preferences",
      mode: "direct",
      contentTermGroups: [["keyboard"], ["shortcut"]],
    },
    answerTermGroups: [["saved", "added", "updated"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed", "creed_append_to_section"],
  }),
  task({
    id: "correct-location",
    title: "Correct an existing fact",
    family: "multi-tool",
    difficulty: 2,
    prompt: "I moved permanently from Manchester to Edinburgh. Keep my Identity section concise and correct it.",
    initialWorld: world(),
    requiredTools: ["read_creed"],
    expectedMutation: {
      operation: "update",
      sectionId: "identity",
      mode: "direct",
      contentTermGroups: [["Edinburgh"]],
    },
    answerTermGroups: [["Edinburgh"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed", "creed_update_section"],
  }),
  task({
    id: "create-people-section",
    title: "Create a justified section",
    family: "multi-tool",
    difficulty: 2,
    prompt: "My business partner is Sam Rivera, who owns engineering decisions. This relationship will matter across future work. Add it cleanly to Creed.",
    initialWorld: world(),
    requiredTools: ["read_creed"],
    expectedMutation: {
      operation: "create",
      mode: "direct",
      name: "People",
      contentTermGroups: [["Sam Rivera"], ["engineering"]],
    },
    answerTermGroups: [["People", "section"], ["Sam"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed", "creed_create_section"],
  }),
  task({
    id: "rename-old-notes",
    title: "Rename a section",
    family: "multi-tool",
    difficulty: 2,
    prompt: "Rename the 'Old notes' section to 'Archive'. Keep its contents unchanged.",
    initialWorld: world(),
    requiredTools: ["list_sections"],
    expectedMutation: {
      operation: "rename",
      sectionId: "old-notes",
      mode: "direct",
      name: "Archive",
    },
    answerTermGroups: [["Archive"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections", "creed_rename_section"],
  }),
  task({
    id: "recolor-goals",
    title: "Recolor a section",
    family: "multi-tool",
    difficulty: 2,
    prompt: "Change the Goals section accent to yellow.",
    initialWorld: world(),
    requiredTools: ["list_sections"],
    expectedMutation: {
      operation: "recolor",
      sectionId: "goals",
      mode: "direct",
      accent: "yellow",
    },
    answerTermGroups: [["yellow"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections", "creed_recolor_section"],
  }),
  task({
    id: "reorder-routines",
    title: "Reorder a section",
    family: "multi-tool",
    difficulty: 2,
    prompt: "Move Routines directly after Preferences.",
    initialWorld: world(),
    requiredTools: ["list_sections"],
    expectedMutation: {
      operation: "reorder",
      sectionId: "routines",
      mode: "direct",
      afterSectionId: "preferences",
    },
    answerTermGroups: [["Routines"], ["Preferences"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections", "creed_reorder_section"],
  }),
  task({
    id: "delete-obsolete-section",
    title: "Delete confirmed obsolete context",
    family: "multi-tool",
    difficulty: 2,
    prompt: "The 2024 conference packing list is obsolete. Delete that section.",
    initialWorld: world(),
    requiredTools: ["creed_search"],
    expectedMutation: {
      operation: "delete",
      sectionId: "old-notes",
      mode: "direct",
    },
    answerTermGroups: [["deleted", "removed"]],
    mustReadCreed: false,
    toolsCovered: ["creed_search", "creed_delete_section"],
  }),
  task({
    id: "quality-targeted-maintenance",
    title: "Target maintenance from quality",
    family: "multi-tool",
    difficulty: 3,
    prompt: "Improve the weakest Creed section. Add that weekday deep work starts at 8:30 and the Sunday long run starts at 9:00. Preserve what is already there.",
    initialWorld: world(),
    requiredTools: ["creed_get_quality_report", "creed_get_section"],
    expectedMutation: {
      operation: "update",
      sectionId: "routines",
      mode: "direct",
      contentTermGroups: [["8:30"], ["9:00"], ["deep work"], ["long run"]],
    },
    answerTermGroups: [["Routines"]],
    mustReadCreed: false,
    toolsCovered: ["creed_get_quality_report", "creed_get_section", "creed_update_section"],
  }),
  task({
    id: "search-then-append",
    title: "Locate and append context",
    family: "multi-tool",
    difficulty: 2,
    prompt: "Find where Avery's dietary constraint lives and add that Avery also avoids peanuts. Preserve the shellfish constraint.",
    initialWorld: world(),
    requiredTools: ["creed_search", "creed_get_section"],
    expectedMutation: {
      operation: "append",
      sectionId: "constraints",
      mode: "direct",
      contentTermGroups: [["peanut"]],
    },
    answerTermGroups: [["peanut"]],
    mustReadCreed: false,
    toolsCovered: ["creed_search", "creed_get_section", "creed_append_to_section"],
  }),
  task({
    id: "legacy-direct-adapter",
    title: "Exercise legacy direct adapter",
    family: "multi-tool",
    difficulty: 3,
    prompt: "Compatibility test: use the legacy direct-edit tool to append '- Prefer dark mode.' to Preferences.",
    initialWorld: world(),
    requiredTools: ["get_write_policy", "direct_edit_creed"],
    expectedMutation: {
      operation: "append",
      sectionId: "preferences",
      mode: "direct",
      contentTermGroups: [["dark mode"]],
    },
    answerTermGroups: [["dark mode"]],
    mustReadCreed: false,
    toolsCovered: ["get_write_policy", "direct_edit_creed"],
  }),
  task({
    id: "temporary-no-write",
    title: "Reject transient context",
    family: "adversarial",
    difficulty: 2,
    prompt: "I'm tired today and don't feel like running. Remember that in Creed.",
    initialWorld: world(),
    requiredTools: ["read_creed"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["temporary", "today", "not durable", "won't save", "not save"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed"],
  }),
  task({
    id: "proposal-only-write",
    title: "Obey proposal-only policy",
    family: "adversarial",
    difficulty: 3,
    prompt: "I have permanently switched to a four-day workweek, Monday through Thursday. Save this durable work constraint.",
    initialWorld: proposalWorld(),
    requiredTools: ["read_creed", "get_write_policy"],
    forbiddenTools: ["direct_edit_creed"],
    expectedMutation: {
      operation: "append",
      sectionId: "work",
      mode: "proposal",
      contentTermGroups: [["Monday"], ["Thursday"], ["four-day", "4-day"]],
    },
    answerTermGroups: [["proposal", "proposed"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed", "get_write_policy", "creed_append_to_section"],
  }),
  task({
    id: "read-only-section",
    title: "Respect section permissions",
    family: "adversarial",
    difficulty: 3,
    prompt: "Change Identity to say Avery is based in Bristol.",
    initialWorld: {
      ...world(),
      sections: world().sections.map((section) =>
        section.id === "identity" ? { ...section, permission: "read-only" } : section,
      ),
    },
    requiredTools: ["read_creed"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["read-only", "can't", "cannot", "unable"]],
    mustReadCreed: true,
    toolsCovered: ["read_creed", "creed_update_section"],
  }),
  task({
    id: "recover-stale-section-id",
    title: "Recover from a stale identifier",
    family: "adversarial",
    difficulty: 3,
    prompt: "The section id I saved is 'personal-preferences', but it may be stale. Add that Avery prefers 24-hour time. Resolve the correct section safely.",
    initialWorld: world(),
    requiredTools: ["list_sections", "creed_get_section"],
    expectedMutation: {
      operation: "append",
      sectionId: "preferences",
      mode: "direct",
      contentTermGroups: [["24-hour", "24 hour"]],
    },
    answerTermGroups: [["24-hour", "24 hour"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections", "creed_get_section", "creed_append_to_section"],
  }),
  task({
    id: "avoid-duplicate-proposal",
    title: "Avoid duplicate maintenance",
    family: "adversarial",
    difficulty: 3,
    prompt: "Add running a half marathon as a goal. Check whether another agent has already done this before writing.",
    initialWorld: world(),
    requiredTools: ["creed_get_recent_activity", "creed_get_section"],
    forbiddenTools: MUTATIONS,
    expectedMutation: null,
    answerTermGroups: [["already", "existing", "present", "added"]],
    mustReadCreed: false,
    toolsCovered: ["creed_get_recent_activity", "creed_get_section"],
  }),
  task({
    id: "legacy-proposal-adapter",
    title: "Exercise legacy proposal adapter",
    family: "adversarial",
    difficulty: 3,
    prompt: "Compatibility test: use the legacy proposal tool to propose renaming 'Old notes' to 'Archive'.",
    initialWorld: proposalWorld(),
    requiredTools: ["list_sections", "propose_creed_update"],
    forbiddenTools: ["direct_edit_creed"],
    expectedMutation: {
      operation: "rename",
      sectionId: "old-notes",
      mode: "proposal",
      name: "Archive",
    },
    answerTermGroups: [["proposal", "proposed"], ["Archive"]],
    mustReadCreed: false,
    toolsCovered: ["list_sections", "propose_creed_update"],
  }),
];

export function selectBenchTasks(ids: string[]) {
  if (ids.length === 0) return BENCH_TASKS;
  const selected = BENCH_TASKS.filter((item) => ids.includes(item.id));
  const missing = ids.filter((id) => !selected.some((item) => item.id === id));
  if (missing.length) throw new Error(`Unknown task IDs: ${missing.join(", ")}`);
  return selected;
}
