"use client";

import { useEffect, useState } from "react";
import { AnimatedPageTitle, AnimatedSectionHeading } from "@/components/marketing/animated-page-title";
import { MarketingFooter, MarketingHeroBanner } from "@/components/marketing/site-chrome";
import { CONTACT_EMAIL, LEGAL_OPERATOR_NAME } from "@/lib/branding";
import { useCreedEdition } from "@/components/creed/edition-provider";

const contactEmail = CONTACT_EMAIL;

type TermsSection = {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  note?: string;
};

const introParagraphs = [
  `These Terms of Service govern your use of Creed, a service operated by ${LEGAL_OPERATOR_NAME}. By using Creed, you agree to these Terms. If you do not agree, do not use the service.`,
];

const cloudSections: TermsSection[] = [
  {
    id: "scope",
    title: "1. Who these Terms apply to",
    paragraphs: [
      "These Terms apply to anyone who accesses or uses Creed, whether during a free period, beta period, or paid access period.",
    ],
  },
  {
    id: "about",
    title: "2. About Creed",
    paragraphs: [
      "Creed is a software product that helps users create, manage, and share a canonical context file across connected AI agents and tools.",
      "Creed may include features such as onboarding, file editing, connected-agent access, proposal review, activity history, and integrations with third-party services.",
    ],
  },
  {
    id: "account",
    title: "3. Your account",
    paragraphs: [
      "You may need to sign in to use Creed.",
      "You are responsible for:",
    ],
    bullets: [
      "keeping your account secure",
      "keeping your login details and access methods private",
      "all activity that happens under your account",
    ],
    note: `If you believe your account has been accessed without permission, contact ${contactEmail}.`,
  },
  {
    id: "content",
    title: "4. Your content",
    paragraphs: [
      "You keep ownership of the content you create, upload, or store in Creed, including your Creed file, onboarding answers, edits, proposals, and related content.",
      "You give Creed a limited right to host, process, store, transmit, and display that content only as needed to operate and improve the service for you.",
      "This does not give Creed ownership of your content.",
    ],
  },
  {
    id: "agent-generated",
    title: "5. Agent-generated changes",
    paragraphs: [
      "Creed may allow connected agents to read your Creed and suggest or submit updates.",
      "You are responsible for deciding whether to accept, reject, or rely on agent-generated content or changes.",
      "Creed is not responsible for incorrect, incomplete, misleading, or unwanted outputs generated by connected agents or third-party AI systems.",
    ],
  },
  {
    id: "payments",
    title: "6. Payments",
    paragraphs: [
      "Creed Open is free to self-host. Creed Cloud is offered as a recurring subscription under the terms shown at checkout.",
      "If and when paid access is introduced:",
    ],
    bullets: [
      "pricing will be shown clearly before purchase",
      "payments will be processed by Stripe or another payment provider",
      "payment card details will not be stored directly by Creed",
    ],
    note: "Unless required by law, payments are non-refundable.",
  },
  {
    id: "commercial-use",
    title: "7. Commercial use",
    paragraphs: ["You may use Creed for personal or commercial work."],
  },
  {
    id: "third-party",
    title: "8. Third-party services",
    paragraphs: [
      "Creed relies on third-party services to operate parts of the product, including services for hosting, authentication, payments, and AI processing.",
      "Creed is not responsible for outages, errors, or changes caused by third-party providers.",
      "Your use of those services may also be subject to their own terms and policies.",
    ],
  },
  {
    id: "availability",
    title: "9. Availability and changes",
    paragraphs: [
      "Creed is provided on an “as is” and “as available” basis.",
      "Creed may change, improve, suspend, or remove features at any time, including during early or free stages of the product.",
      "No guarantee is made that the service will always be available, uninterrupted, secure, or error-free.",
    ],
  },
  {
    id: "termination",
    title: "10. Suspension and termination",
    paragraphs: [
      "Creed may suspend or terminate access to the service if:",
    ],
    bullets: [
      "these Terms are breached",
      "use of the service creates risk, harm, or legal exposure",
      "the service is being misused in a way that affects Creed or other users",
    ],
    note:
      "You may stop using Creed at any time. If your account is terminated or deleted, some information may be retained where reasonably necessary for legal, operational, fraud-prevention, or record-keeping purposes.",
  },
  {
    id: "privacy",
    title: "11. Privacy",
    paragraphs: [
      "Your use of Creed is also governed by the Privacy Policy.",
      "Please read the Privacy Policy to understand how Creed collects, uses, and stores personal information.",
    ],
  },
  {
    id: "liability",
    title: "12. Liability",
    paragraphs: [
      "To the fullest extent allowed by law, Creed is not liable for any indirect, incidental, special, consequential, or loss-of-profit damages arising from or related to your use of the service.",
      "Creed is also not liable for:",
    ],
    bullets: [
      "loss caused by agent-generated errors",
      "loss caused by third-party service outages",
      "loss caused by your own acceptance or use of generated updates",
      "loss of business, revenue, profits, data, goodwill, or opportunity",
    ],
    note: "Nothing in these Terms excludes or limits liability where it would be unlawful to do so.",
  },
  {
    id: "changes",
    title: "13. Changes to these Terms",
    paragraphs: [
      "Creed may update these Terms from time to time.",
      "If the Terms are updated, the revised version will be posted on this page.",
      "By continuing to use Creed after changes take effect, you agree to the updated Terms.",
    ],
  },
  {
    id: "law",
    title: "14. Governing law",
    paragraphs: [
      "These Terms are governed by the laws of the United Kingdom.",
      "Any disputes relating to these Terms or your use of Creed will be subject to the applicable courts of the United Kingdom.",
    ],
  },
  {
    id: "contact",
    title: "15. Contact",
    paragraphs: [
      "If you have questions about these Terms, contact:",
    ],
    note: contactEmail,
  },
];

const openIntroParagraphs = [
  "These terms cover the official Creed website and Creed Open software. The software is also provided under the MIT License included in the repository.",
];

const openSections: TermsSection[] = [
  {
    id: "about",
    title: "1. About Creed Open",
    paragraphs: [
      "Creed Open is self-hosted software for creating and maintaining a personal context file across connected AI agents.",
      "You choose where it runs and which third-party services it connects to.",
    ],
  },
  {
    id: "license",
    title: "2. Software license",
    paragraphs: [
      "The repository's MIT License grants permission to use, copy, modify, merge, publish, distribute, sublicense, and sell copies subject to its notice and disclaimer requirements.",
      "If these website terms conflict with the MIT License about use of the software, the MIT License controls.",
    ],
  },
  {
    id: "installation",
    title: "3. Your installation",
    bullets: [
      "protect owner, database, encryption, and integration secrets",
      "apply security updates and database migrations",
      "configure backups and access controls",
      "follow laws that apply to the data you store or process",
    ],
    note: "You are responsible for activity and data in an installation you operate.",
  },
  {
    id: "content",
    title: "4. Your content",
    paragraphs: [
      "You keep ownership of content you create or store in Creed Open. Running the software does not transfer ownership of that content to the Creed project.",
    ],
  },
  {
    id: "agents",
    title: "5. Connected agents",
    paragraphs: [
      "Connected agents and AI providers can produce incorrect, incomplete, or unwanted output. Review credentials, permissions, proposals, and direct edits before relying on them.",
    ],
  },
  {
    id: "third-party",
    title: "6. Third-party services",
    paragraphs: [
      "Supabase is required for the current release. Hosting, OpenRouter, GitHub, and other integrations are chosen and configured by the operator and are governed by their own terms.",
      "The Creed project is not responsible for third-party outages, policy changes, charges, or data handling.",
    ],
  },
  {
    id: "availability",
    title: "7. Availability and warranty",
    paragraphs: [
      "Creed Open is provided under the warranty disclaimer in the MIT License. No guarantee is made that the software or official website will always be available, uninterrupted, secure, or error-free.",
    ],
  },
  {
    id: "liability",
    title: "8. Liability",
    paragraphs: [
      "Liability is limited to the fullest extent allowed by applicable law and subject to the MIT License. Nothing excludes liability where doing so would be unlawful.",
    ],
  },
  {
    id: "changes",
    title: "9. Changes",
    paragraphs: [
      "These website terms may change when the official website or project changes. The license terms for a copy of the software remain those shipped with that copy.",
    ],
  },
  {
    id: "contact",
    title: "10. Contact",
    paragraphs: ["Questions about these terms can be sent to:"],
    note: contactEmail,
  },
];

export function TermsPageView() {
  const hostedAccounts = useCreedEdition().capabilities.hostedAccounts;
  const activeIntroParagraphs = hostedAccounts ? introParagraphs : openIntroParagraphs;
  const sections = hostedAccounts ? cloudSections : openSections;
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    function onScroll() {
      setScrolled(window.scrollY > 20);
    }

    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <div className="min-h-screen bg-[var(--creed-background)] text-[var(--creed-text-primary)]">
      <MarketingHeroBanner configured scrolled={scrolled} />

      <main className="mx-auto max-w-3xl px-6 pb-20 pt-8 md:px-10 md:pb-24 md:pt-10">
        <div className="border-b border-[var(--creed-border)] pb-8">
          <AnimatedPageTitle text="Terms and Conditions" />
        </div>

        <div className="border-b border-[var(--creed-border)] pb-8 pt-8 text-[var(--creed-text-secondary)]">
          <div className="space-y-4 text-[16px] leading-8 md:text-[17px]">
            {activeIntroParagraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </div>
        </div>

        <div className="pt-2">
          {sections.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className={section.id === "contact" ? "py-8 md:py-10" : "border-b border-[var(--creed-border)] py-8 md:py-10"}
            >
              <AnimatedSectionHeading text={section.title} className="t-step" />

              <div className="mt-5 space-y-4 text-[15px] leading-8 text-[var(--creed-text-secondary)] md:text-[16px]">
                {section.paragraphs?.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </div>

              {section.bullets ? (
                <ol className="mt-5 list-decimal space-y-3 pl-5 text-[15px] leading-8 text-[var(--creed-text-secondary)] marker:font-medium marker:text-[var(--creed-accent)] md:text-[16px]">
                  {section.bullets.map((item) => (
                    <li key={item} className="pl-1 first-letter:uppercase">{item}</li>
                  ))}
                </ol>
              ) : null}

              {section.note ? (
                section.id === "contact" ? (
                  <a
                    href={`mailto:${section.note}`}
                    className="mt-5 inline-block font-medium text-[15px] leading-8 text-[var(--creed-accent)] transition-colors hover:text-[var(--creed-accent-hover)] md:text-[16px]"
                  >
                    {section.note}
                  </a>
                ) : (
                  <p className="mt-5 text-[15px] leading-8 text-[var(--creed-text-primary)] md:text-[16px]">
                    {section.note}
                  </p>
                )
              ) : null}
            </section>
          ))}
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
